name: dartcoin
description: A simple Dart library for bitcoin wallets.
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
  bip39: ^1.0.6
  benchmark_runner: ^2.0.1
