name: bitcoin_play
description: A simple Dart project for bitcoin experiments.
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  crypto: ^3.0.6
  cryptography: ^2.7.0
  hashlib: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
  bip39: ^1.0.6